name: ynotes
description: yNotes application de gestion de vie scolaire

version: 0.12.1+9
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  battery_optimization:
    git:
      url: https://github.com/ChangJoo-Park/battery_optimization
      ref: master
  ext_storage:
    git:
      url: https://github.com/GitJournal/ext_storage
      ref: master
  flutter_secure_storage: ^4.2.1
  requests:
    git:
      url: https://github.com/ianmaciel/requests
      ref: feature/null-safety
  settings_ui:
    git:
      url: https://github.com/EduWireApps/flutter-settings-ui
      ref: master
  simple_animations:
    git:
      url: https://github.com/felixblaschke/simple_animations
      ref: nullsafety3
  tinycolor:
    git:
      url: https://github.com/lslv1243/tinycolor
      ref: master
  wiredash:
    git:
      url: https://github.com/wiredashio/wiredash-sdk
      ref: stable
  ynotes_packages:
    git:
      url: https://github.com/EduWireApps/ynotes-packages
      ref: main
  android_alarm_manager: ^2.0.0
  another_flushbar: ^1.10.17
  auto_size_text: ^3.0.0-nullsafety.0
  awesome_notifications: ^0.0.6+7
  background_fetch: ^1.0.0-nullsafety.2
  calendar_time: ^2.0.0-nullsafety.0
  connectivity_plus: ^1.0.2
  csv: ^5.0.0
  date_field: ^2.0.1
  dotted_line: ^3.0.0
  encrypt: ^5.0.0
  expandable: ^5.0.1
  fl_chart: ^0.35.0
  flare_flutter: ^3.0.0
  flutter_file_dialog: ^2.0.0
  flutter_inappwebview: ^5.3.2
  flutter_markdown: ^0.6.1
  flutter_phoenix: ^1.0.0
  flutter_responsive_breakpoints: ^0.0.3
  flutter_slidable: ^0.6.0-nullsafety.0
  flutter_spinkit: ^5.0.0
  flutter_staggered_grid_view: ^0.4.0
  flutter_tex: ^4.0.1
  flutter_typeahead: ^3.1.3
  flutter_widget_from_html_core: ^0.6.0-rc.2021031201
  font_awesome_flutter: ^9.1.0
  geolocator: ^7.0.3
  hive: ^2.0.2
  hive_flutter: ^1.0.0
  html_character_entities: ^1.0.0+1
  html_editor_enhanced: ^1.8.0
  http: ^0.13.0
  intl: ^0.16.1
  json_annotation: ^4.0.1
  liquid_progress_indicator_ns: ^1.0.0
  logger: ^1.0.0
  marquee: ^2.0.0
  material_design_icons_flutter: ^5.0.5955-rc.1
  open_file: ^3.0.1
  package_info: ^2.0.0
  path_provider: ^2.0.1
  permission_handler: ^6.1.1
  pin_code_fields: ^7.2.0
  pointycastle: ^3.0.1
  preload_page_view: ^0.1.6
  provider: ^5.0.0
  qr_code_scanner: ^0.5.1
  rive: ^0.7.18
  share: ^2.0.1
  shared_preferences: ^2.0.5
  shimmer: ^2.0.0-nullsafety.0
  sizer: ^2.0.13
  sliding_up_panel: ^2.0.0+1
  smooth_page_indicator: ^0.3.0-nullsafety.0
  stack: ^0.2.1
  stacked: ^2.0.2
  supabase: ^0.0.3
  supercharged: ^2.0.0
  url_launcher: ^6.0.3
  uuid: ^3.0.3
dependency_overrides:
  intl: ^0.17.0-nullsafety.2
  mime: ^1.0.0
  args: ^2.1.1
  markdown: ^4.0.0
  build: ^2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.4
  hive_generator: ^1.0.1
  json_serializable: ^4.1.0
  dependency_validator: ^3.1.0 # flutter pub run dependency_validator
flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/appico/icon.png"
  image_path_android: "assets/appico/icon.png"
  adaptive_icon_background: "#ffff"
  adaptive_icon_foreground: "assets/appico/foreground.png"

flutter:
  uses-material-design: true
  fonts:
    - family: Asap
      fonts:
        - asset: fonts/Asap-Regular.ttf
        - asset: fonts/Asap-Medium.ttf
          weight: 500
        - asset: fonts/Asap-SemiBold.ttf
          weight: 600
        - asset: fonts/Asap-Bold.ttf
          weight: 700
        - asset: fonts/Asap-Italic.ttf
          style: italic
        - asset: fonts/Asap-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: fonts/Asap-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: fonts/Asap-BoldItalic.ttf
          style: italic
          weight: 700

  assets:
    - assets/animations/
    - assets/images/
    - assets/images/icons/pronote/
    - assets/images/icons/ecoledirecte/
    - assets/images/icons/laviescolaire/
    - assets/images/icons/app/
    - assets/images/pageItems/agenda/
    - assets/images/pageItems/carousel/shelves/
    - assets/images/pageItems/carousel/
    - assets/images/pageItems/grades/
    - assets/images/pageItems/homework/
    - assets/images/pageItems/persistantNotification/
    - assets/images/pageItems/login/
    - assets/documents/updateNoteAssets/
    - assets/appico/
    - assets/appico/foreground.png
    - assets/documents/TOS_fr.txt
