name: ynotes
description: yNotes application de gestion de vie scolaire

# Don't delete the `+9`
#
# Before building the app for Windows, go to `windows/runner/Runner.rc` and edit `VERSION_AS_NUMBER` and `VERSION_AS_STRING`
version: 0.14.7+9
publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  background_fetch: ^1.0.3
  optimize_battery: ^0.0.2
  connectivity_plus: ^2.2.0
  encrypt: ^5.0.1
  fl_chart: ^0.41.0
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.3.2
  flutter_localizations:
    sdk: flutter
  flutter_map: ^0.14.0
  flutter_markdown: ^0.6.9
  flutter_phoenix: ^1.0.0
  flutter_secure_storage: ^5.0.2
  flutter_spinkit: ^5.1.0
  focus_detector: ^2.0.1
  font_awesome_flutter: ^9.2.0
  geolocator: ^8.0.3
  google_fonts: ^2.2.0
  html_character_entities: ^1.0.0+1
  html_unescape: ^2.0.0
  isar: ^2.1.0
  isar_flutter_libs: ^2.1.0 # contains the binaries
  http: ^0.13.4
  intl: ^0.17.0
  json_annotation: ^4.4.0
  latlong2: ^0.8.1
  material_design_icons_flutter: ^5.0.6595
  open_file: ^3.2.1
  package_info_plus: ^1.3.0
  path_provider: ^2.0.8
  permission_handler: ^8.3.0
  pointycastle: ^3.5.0
  provider: ^6.0.2
  qr_code_scanner: ^0.6.1
  shake_flutter: ^15.1.0
  simple_animations: ^4.0.1
  smooth_page_indicator: ^1.0.0+2
  url_launcher: ^6.0.18
  uuid: ^3.0.5
  ynotes_packages:
    git:
      ref: main
      url: "https://github.com/EduWireApps/ynotes-packages"
  dotted_border: ^2.0.0+2
  flutter_local_notifications: ^9.2.0
  collection: ^1.15.0
  convert: ^3.0.1
  crypto: ^3.0.1
  html: ^0.15.0
  path: ^1.8.0
  queue: ^3.1.0+1

# dependency_overrides:

dev_dependencies:
  isar_generator: ^2.1.0
  build_runner: ^2.0.4 # flutter packages pub run build_runner build --delete-conflicting-outputs
  dependency_validator: ^3.1.0 # flutter pub run dependency_validator
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.4

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/appico/icon.png"
  image_path_android: "assets/appico/icon.png"
  adaptive_icon_background: "#ffff"
  adaptive_icon_foreground: "assets/appico/foreground.png"

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/images/
    - assets/images/icons/pronote/
    - assets/images/icons/ecoledirecte/
    - assets/images/icons/laviescolaire/
    - assets/images/icons/app/
    - assets/images/pageItems/agenda/
    - assets/images/pageItems/grades/
    - assets/images/pageItems/homework/
    - assets/images/pageItems/persistantNotification/
    - assets/images/pageItems/login/
    - assets/documents/patchNotes/
    - assets/appico/
    - assets/appico/foreground.png
    - assets/documents/TOS_fr.txt
    - assets/images/pageItems/intro/slide1/background.png
    - assets/images/pageItems/intro/slide1/bubble.png
    - assets/images/pageItems/intro/slide1/woman.png
    - assets/images/pageItems/intro/slide2/notif1.png
    - assets/images/pageItems/intro/slide2/notif2.png
    - assets/images/pageItems/intro/slide2/phone.png
    - assets/images/pageItems/intro/slide3/lock.png
    - assets/images/pageItems/intro/slide3/man.png
    - assets/images/pageItems/intro/slide3/page1.png
    - assets/images/pageItems/intro/slide3/page2.png
