name: ynotes
description: yNotes application de gestion de vie scolaire

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.

version: 0.9.2+9

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^3.3.3
  auto_size_text: ^2.1.0
  http: ^0.12.0+4
  charts_flutter: ^0.8.1
  circular_check_box: ^1.0.1
  shimmer: ^1.0.1
  badges: ^1.1.0
  intl: ^0.16.1
  stack: ^0.1.3
  tinycolor: ^1.0.2
  flutter_spinkit: ^4.1.2
  material_design_icons_flutter: ^3.4.5045
  simple_animations:
    git:
      url: https://github.com/felixblaschke/simple_animations
      ref: master
  provider: ^4.3.2+2
  flutter_widget_from_html_core: ^0.5.1+4
  path_provider: ^1.6.11
  marquee: ^1.3.1
  url_launcher: ^5.5.0
  stacked: ^1.6.0
  alice: ^0.0.33
  open_file: ^3.0.1
  flushbar: ^1.10.4
  hive: ^1.5.0-pre
  hive_flutter: ^0.3.1
  flutter_local_notifications: ^1.4.3
  connectivity: ^0.4.8+6
  background_fetch: ^0.6.0
  scrollable_positioned_list: ^0.1.6
  package_info: ^0.4.0+16
  share: ^0.6.4+3
  requests: ^3.3.0
  encrypt: ^4.0.2
  pointycastle: ^1.0.2
  dio: ^3.0.9
  uuid: ^2.1.0
  highlight_text: ^0.7.2
  device_apps: ^1.0.10
  rxdart: ^0.24.1
  smooth_page_indicator: ^0.1.5
  percent_indicator: ^2.1.5
  ext_storage: ^1.0.3
  permission_handler: ^5.0.1+1
  build_resolvers: ^1.4.1
  settings_ui: ^0.4.0
  android_alarm_manager: ^0.4.5+11
  workmanager: ^0.2.3
  visibility_detector: ^0.1.5
  dotted_line: ^2.0.1
  flutter_slidable: ^0.5.7
  json_annotation: ^3.0.0
  flare_flutter: ^2.0.6
  zefyr: ^0.12.0
  calendar_time: ^1.0.1
  flutter_phoenix: ^0.1.0
  showcaseview: ^0.1.6
  animated_text_kit: ^2.5.4
  battery_optimization: ^0.1.0
  flutter_dnd: ^0.1.3
  awesome_notifications: ^0.0.5+2
  pull_to_refresh: ^1.6.1
  flutter_markdown: ^0.5.0
  html_editor:
     path: ./lib/ui/components/flutter-html-editor
  popup_menu: ^1.0.5
  floating_action_bubble: ^1.1.2
  catex: ^0.0.1+7
  flutter_tex: ^3.6.7+10
  fl_chart: ^0.12.0
  expandable: ^4.1.4
  liquid_progress_indicator: ^0.3.2
  dotted_border: ^1.0.7

  wiredash:
    git:
      url: https://github.com/wiredashio/wiredash-sdk
      ref: master
  flutter_file_dialog: ^0.0.5
  advance_pdf_viewer: ^1.2.1+2

dependency_overrides:
  analyzer: ^0.40.4
  intl: ^0.16.1
  webview_flutter: ^1.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4
  hive_generator: ^0.8.1
  build_runner: ^1.10.3
  json_serializable: ^3.5.1
  dependency_validator: ^1.0.0
flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/appico/icon.png"
  image_path_android: "assets/appico/icon.png"
  adaptive_icon_background: "#ffff"
  adaptive_icon_foreground: "assets/appico/foreground.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: Asap
      fonts:
        - asset: fonts/Asap-Regular.otf
        - asset: fonts/Asap-Italic.otf
          style: italic
        - asset: fonts/Asap-Bold.otf
          weight: 700
    - family: ProximaNova
      fonts:
        - asset: fonts/proxima-nova-soft-bold.otf
          weight: 700

  assets:
    - assets/images/logoED.svg
    - assets/images/space/space.png
    - assets/images/space/2.0x/space.png
    - assets/images/space/4.0x/space.png
    - assets/images/marks/2.0x/mark.png
    - assets/images/marks/3.0x/mark.png
    - assets/images/marks/mark.png
    - assets/images/shelves/calendar.png
    - assets/images/shelves/clock.png
    - assets/images/shelves/shelve1.png
    - assets/images/shelves/shelve2.png
    - assets/images/totor.png
    - assets/images/book.png
    - assets/animations/
    - assets/images/
    - assets/images/persistantNotification/
    - assets/images/Pronote/
    - assets/images/EcoleDirecte/
    - assets/appico/
    - assets/appico/foreground.png
    - assets/gifs/
    - assets/TOS_fr.txt
    - assets/updateNoteAssets/
