blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ FAQ
    url: https://ynotes.fr/faq/
    about: |
      Une question ? La rÃ©ponse se trouve peut-Ãªtre dans la FAQ.
  - name: â“ Centre d'aide
    url: https://support.ynotes.fr/
    about: |
      De votre compte Ã  notre politique de confidentialitÃ©, vous trouverez ici toute l'aide dont vous avez besoin.
  - name: â—ï¸ Toutes les autres questions
    url: https://discord.gg/pRCBs22dNX
    about: |
      Veuillez utiliser le serveur Discord pour les autres problÃ¨mes et pour poser des questions.